openapi: 3.0.1
info:
  title: API DENDOL
  description: "Dokumentasi API Cendana Online"
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/v1
tags:
  - name: Auth
  - name: Iuran
  - name: Agenda
  - name: Pengumuman
paths:
  /auth:
    post:
      tags:
        - Auth
      summary: get token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - "username"
                - "password"
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: OK.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        401:
          $ref: "./responses/common.yaml#/components/responses/500"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
  /whoami:
    get:
      tags:
        - Auth
      summary: get profile
      security:
        - bearerAuth: []
      responses:
        200:
          $ref: "./responses/common.yaml#/components/responses/200"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
  /iuran:
    get:
      tags:
        - Iuran
      summary: list history iuran
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          description: limit of data (default = 5)
          in: query
          schema:
            type: string
            format: string
        - name: offset
          in: query
          schema:
            type: string
            format: string
      responses:
        200:
          $ref: "./responses/common.yaml#/components/responses/200_pagination"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
    post:
      tags:
        - Iuran
      summary: bayar iuran
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - "periode"
                - "bukti"
              properties:
                periode:
                  type: string
                bukti:
                  type: string
                  format: binary
      responses:
        201:
          $ref: "./responses/common.yaml#/components/responses/201"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
  /iuran/approve:
    post:
      tags:
        - Iuran
      summary: approve iuran
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - "id"
              properties:
                id:
                  type: string
      responses:
        201:
          $ref: "./responses/common.yaml#/components/responses/201"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
  /agenda:
    get:
      tags:
        - Agenda
      summary: list agenda
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          description: limit of data (default = 5)
          in: query
          schema:
            type: string
            format: string
        - name: offset
          in: query
          schema:
            type: string
            format: string
      responses:
        200:
          $ref: "./responses/common.yaml#/components/responses/200_pagination"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
    post:
      tags:
        - Agenda
      summary: buat agenda
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - "periode"
                - "bukti"
              properties:
                judul:
                  type: string
                foto:
                  type: string
                  format: binary
                deskripsi:
                  type: string
                tanggal:
                  type: string
                  format: date-time
      responses:
        201:
          $ref: "./responses/common.yaml#/components/responses/201"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
  /pengumuman:
    get:
      tags:
        - Pengumuman
      summary: list pengumuman
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          description: limit of data (default = 5)
          in: query
          schema:
            type: string
            format: string
        - name: offset
          in: query
          schema:
            type: string
            format: string
      responses:
        200:
          $ref: "./responses/common.yaml#/components/responses/200_pagination"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
    post:
      tags:
        - Pengumuman
      summary: buat pengumuman
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - "periode"
                - "bukti"
              properties:
                judul:
                  type: string
                is_urgent:
                  type: string
                is_sticky:
                  type: string
                deskripsi:
                  type: string
                tanggal:
                  type: string
                  format: date-time
                tanggal_takeout:
                  type: string
                  format: date-time
      responses:
        201:
          $ref: "./responses/common.yaml#/components/responses/201"
        400:
          $ref: "./responses/common.yaml#/components/responses/400"
        500:
          $ref: "./responses/common.yaml#/components/responses/500"
      
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 